import obsidianmd from 'eslint-plugin-obsidianmd';
import globals from 'globals';
import { globalIgnores, defineConfig } from 'eslint/config';

export default defineConfig(
	globalIgnores([
		'node_modules',
		'dist',
		'esbuild.config.mjs',
		'version-bump.mjs',
		'versions.json',
		'main.js',
		'package.json',
		'package-lock.json',
		'tsconfig.json',
	]),
	{
		languageOptions: {
			globals: {
				...globals.browser,
			},
			parserOptions: {
				projectService: {
					allowDefaultProject: ['eslint.config.mts', 'manifest.json'],
				},
				tsconfigRootDir: import.meta.dirname,
				extraFileExtensions: ['.json'],
			},
		},
	},
	...obsidianmd.configs.recommended,
	{
		rules: {
			// obsidianmd/ui/sentence-case's brand list doesn't include ElevenLabs, so without this
			// override the rule would suggest lowercasing it to "elevenlabs", misspelling the brand.
			// Options replace (not merge with) the rule's defaults, so this repeats them verbatim
			// plus ElevenLabs — see eslint-plugin-obsidianmd's ui/brands.ts for the canonical list.
			'obsidianmd/ui/sentence-case': [
				'warn',
				{
					brands: [
						'iOS',
						'iPadOS',
						'macOS',
						'Windows',
						'Android',
						'Linux',
						'Obsidian',
						'Obsidian Sync',
						'Obsidian Publish',
						'Google',
						'Gemini',
						'Vertex AI',
						'OpenAI',
						'GPT',
						'Anthropic',
						'Claude',
						'Cursor',
						'Microsoft',
						'Google Drive',
						'Dropbox',
						'OneDrive',
						'iCloud Drive',
						'YouTube',
						'Slack',
						'Discord',
						'Telegram',
						'WhatsApp',
						'Twitter',
						'X',
						'Readwise',
						'Zotero',
						'Excalidraw',
						'Mermaid',
						'Markdown',
						'LaTeX',
						'JavaScript',
						'TypeScript',
						'Node.js',
						'npm',
						'pnpm',
						'Yarn',
						'Git',
						'GitHub',
						'GitLab',
						'Anki',
						'CalDAV',
						'CardDAV',
						'Evernote',
						'IntelliJ IDEA',
						'Jekyll',
						'Logseq',
						'Notion',
						'PyCharm',
						'React',
						'Reddit',
						'Roam Research',
						'Svelte',
						'VS Code',
						'Visual Studio Code',
						'WebDAV',
						'WebStorm',
						'ElevenLabs',
					],
					// Same story as brands: options replace rather than merge with defaults, and TTS
					// isn't in the rule's default acronym list, so without this it would be lowercased.
					acronyms: [
						'API',
						'HTTP',
						'HTTPS',
						'URL',
						'DNS',
						'TCP',
						'IP',
						'SSH',
						'TLS',
						'SSL',
						'FTP',
						'SFTP',
						'SMTP',
						'JSON',
						'XML',
						'HTML',
						'CSS',
						'PDF',
						'CSV',
						'YAML',
						'SQL',
						'PNG',
						'JPG',
						'JPEG',
						'GIF',
						'SVG',
						'2FA',
						'MFA',
						'OAuth',
						'JWT',
						'LDAP',
						'SAML',
						'SDK',
						'IDE',
						'CLI',
						'GUI',
						'CRUD',
						'SOAP',
						'CPU',
						'GPU',
						'RAM',
						'SSD',
						'USB',
						'UI',
						'OK',
						'RSS',
						'S3',
						'ID',
						'UUID',
						'GUID',
						'SHA',
						'MD5',
						'ASCII',
						'UTF-8',
						'UTF-16',
						'DOM',
						'CDN',
						'FAQ',
						'AI',
						'ML',
						'LLM',
						'TTS',
					],
				},
			],
		},
	},
);
