import { SettingDefinitionItem, SettingGroupItem } from 'obsidian';
import { DEFAULT_SETTINGS, FALLBACK_TEXT_KEYS } from '../settings';
import { SettingsSection } from '../section';

export class FilesSection extends SettingsSection {
	public definitions(): SettingDefinitionItem[] {
		const visible = this.onTab('files');
		const settings = this.settings;
		const savingOff = () => !settings.saveAudioFile;
		const linkingOff = () => !settings.saveAudioFile || !settings.linkAudioInNote;

		const propertyRow = (name: string, desc: string, key: keyof typeof FALLBACK_TEXT_KEYS): SettingGroupItem => ({
			name,
			desc,
			control: {
				type: 'text',
				key,
				placeholder: DEFAULT_SETTINGS[key] as string,
				defaultValue: DEFAULT_SETTINGS[key] as string,
				disabled: linkingOff,
			},
		});

		return [
			{
				type: 'group',
				heading: 'Saving audio',
				visible,
				items: [
					{
						name: 'Save generated audio to a file',
						desc: 'When enabled, also saves the audio generated by a read as an .mp3 file in the vault, and links it in the note. Disabled by default.',
						control: { type: 'toggle', key: 'saveAudioFile', defaultValue: DEFAULT_SETTINGS.saveAudioFile },
					},
					{
						name: 'Save location',
						desc: 'Where to save the audio file.',
						control: {
							type: 'dropdown',
							key: 'saveAudioLocation',
							options: { 'note-folder': 'Same folder as the note', 'custom-folder': 'Custom folder' },
							defaultValue: DEFAULT_SETTINGS.saveAudioLocation,
							disabled: savingOff,
						},
					},
					{
						name: 'Custom folder path',
						desc: "Vault-relative folder to save audio files in. Created automatically if it doesn't exist.",
						control: {
							type: 'text',
							key: 'saveAudioFolderPath',
							placeholder: DEFAULT_SETTINGS.saveAudioFolderPath,
							defaultValue: DEFAULT_SETTINGS.saveAudioFolderPath,
							disabled: () => savingOff() || settings.saveAudioLocation !== 'custom-folder',
						},
					},
					{
						name: 'On regenerate',
						desc: "What to do when a note's audio already exists and is regenerated: replace the previously linked file, or keep it and create a new one.",
						control: {
							type: 'dropdown',
							key: 'saveVersioning',
							options: { replace: 'Replace existing file', keep: 'Keep old versions' },
							defaultValue: DEFAULT_SETTINGS.saveVersioning,
							disabled: linkingOff,
						},
					},
					{
						name: 'Auto-generate on open',
						desc: 'When enabled, opening a note silently (re)generates and saves its audio in the background if missing or outdated — without playing it or interrupting anything currently playing.',
						control: { type: 'toggle', key: 'autoGenerateOnOpen', defaultValue: DEFAULT_SETTINGS.autoGenerateOnOpen, disabled: linkingOff },
					},
				],
			},
			{
				type: 'group',
				heading: 'Linking in the note',
				visible,
				items: [
					{
						name: 'Link saved audio in the note',
						desc: 'Writes a link to the saved audio file into a frontmatter property on the note, and tracks whether the note has changed since — shown in the player view. On by default; turning on saving turns this on too.',
						control: { type: 'toggle', key: 'linkAudioInNote', defaultValue: DEFAULT_SETTINGS.linkAudioInNote, disabled: savingOff },
					},
					propertyRow('Link property', 'Frontmatter property the audio link is written to.', 'audioLinkProperty'),
					propertyRow('Hash property', 'Frontmatter property the content hash is written to, used to detect staleness.', 'audioHashProperty'),
					propertyRow('Path property', 'Frontmatter property the raw vault path to the audio file is written to (used internally to find it again).', 'audioPathProperty'),
					propertyRow('Timestamp property', 'Frontmatter property the generation timestamp is written to.', 'audioTimestampProperty'),
					propertyRow(
						'Narrator property',
						"Frontmatter property a fingerprint of the narrator profile's voice settings is written to. Used to detect when the selected narrator differs from the one that made the saved audio.",
						'audioVoiceProperty',
					),
					propertyRow(
						'Chunk durations property',
						"Frontmatter property each chunk's [duration, byte length] is written to. Lets the saved file be sliced back into its per-chunk parts, so Previous/Next part and highlighting/scroll-to-current work during \"Play saved\" too -- only while the note is up to date with the saved audio.",
						'audioChunkDurationsProperty',
					),
					{
						name: 'Extra properties to exclude from staleness hashing',
						desc: "Besides Note Narrator's own properties above (always excluded), also ignore these frontmatter properties when checking whether a note has changed since its audio was generated — for properties other plugins auto-update that shouldn't count as a real edit. One property key per line.",
						control: { type: 'textarea', key: 'extraStaleHashExcludedProperties', placeholder: 'last_modified', rows: 3, disabled: linkingOff },
					},
				],
			},
			{
				type: 'group',
				heading: 'Cleanup',
				visible,
				items: [
					{
						name: 'Show "Clear Note Narrator files" menu item and delete button',
						desc: 'Enable the "Clear Note Narrator files" item in the player view\'s ⋮ menu (top-right) and the small delete button on the saved-audio status line, both of which delete a note\'s linked audio file and remove the properties above, after confirming.',
						control: { type: 'toggle', key: 'showClearFilesButton', defaultValue: DEFAULT_SETTINGS.showClearFilesButton, disabled: linkingOff },
					},
					{
						name: 'Auto-clean up properties when saved file is missing',
						desc: "When a note's linked audio file no longer exists (moved or deleted outside Note Narrator), or its path property doesn't name an .mp3 file, silently remove the properties above instead of showing a misleading \"outdated\" status.",
						control: {
							type: 'toggle',
							key: 'autoCleanupMissingAudioProperties',
							defaultValue: DEFAULT_SETTINGS.autoCleanupMissingAudioProperties,
							disabled: linkingOff,
						},
					},
				],
			},
		];
	}
}
